wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.2
    framework: huggingface
    huggingface_version: 4.7.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      2:
      - 1
      - 2
      - 3
      - 11
      3:
      - 2
      4: 3.7.9
      5: 0.11.2
      6: 4.7.0
      8:
      - 1
      - 5
